services:
  db:
    image: postgres:15
    container_name: clinical-sutra-db
    restart: always
    environment: 
       POSTGRES_USER: ${DB_USER} 
       POSTGRES_PASSWORD: ${DB_PASSWORD}
       POSTGRES_DB: ${DB_NAME}

    ports: 
      - "${DB_PORT}:5432" 
    
    volumes: 
      - postgres_data:/var/lib/postgresql/data
      - ./backend/src/sql/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    restart: unless-stopped
    ports:
      - "6333:6333"

    volumes:
      - qdrant_storage:/qdrant/storage
      
volumes:
  postgres_data:
  qdrant_storage:
       
